# For Istio 1.1.7 helm chart 1.1.0
# Kiali Secret
# Replace "username" and "password"

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dashboard.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kiali.name" . }}
    chart: {{ template "kiali.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  username: {{ "_USER_" | b64enc | quote }}
  passphrase: {{ "_PASS_" | b64enc | quote }}
