apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    redis-role: master
spec:
  ports:
  - port: 6379
    name: redis-master
  clusterIP: None
  selector:
    app: redis
    redis-role: master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master
  labels:
    app: redis
    redis-role: master
spec:
  serviceName: redis-master
  selector:
    matchLabels:
      app: redis
      redis-role: master
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
        redis-role: master
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - redis
              - key: redis-role
                operator: In
                values:
                - master
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: redis
        image: redis:5
