# For Istio 1.1.7 helm chart 1.1.0
# Grafana Secret
# Replace "username" and "password"

{{- if .Values.security.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  username: {{ "username" | b64enc | quote }}
  passphrase: {{ "password" | b64enc | quote }}
{{- end }}
