apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-monitor-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: redis-monitor
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: redis-monitor-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-test
  labels:
    app: alpine-test
spec:
  selector:
    matchLabels:
      app: alpine-test
  template:
    metadata:
      labels:
        app: alpine-test
    spec:
      serviceAccountName: redis-monitor-sa
      containers:
      - name: alpine
        image: alpine
        args:
        - /bin/sh
        - -c
        - sleep 7d
