apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb
  namespace: monitor
  labels:
    app: influxdb
    stack: tig
data:
  influxdb.conf: |+
    reporting-disabled = false

    [meta]
      dir = "/var/lib/influxdb/meta"
      retention-autocreate = true
      logging-enabled = true

    [data]
      dir = "/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"
      query-log-enabled = true
      cache-max-memory-size = 1073741824
      cache-snapshot-memory-size = 26214400
      cache-snapshot-write-cold-duration = "10m0s"
      compact-full-write-cold-duration = "4h0m0s"
      max-series-per-database = 1000000
      max-values-per-tag = 100000
      trace-logging-enabled = false

    [coordinator]
      write-timeout = "10s"
      max-concurrent-queries = 0
      query-timeout = "0s"
      log-queries-after = "0s"
      max-select-point = 0
      max-select-series = 0
      max-select-buckets = 0

    [retention]
      enabled = true
      check-interval = "30m0s"

    [shard-precreation]
      enabled = true
      check-interval = "10m0s"
      advance-period = "30m0s"

    [monitor]
      store-enabled = true
      store-database = "_internal"
      store-interval = "10s"

    [subscriber]
      enabled = true
      http-timeout = "30s"
      insecure-skip-verify = false
      ca-certs = ""
      write-concurrency = 40
      write-buffer-size = 1000

    [http]
      enabled = true
      bind-address = ":8086"
      auth-enabled = true
      log-enabled = true
      write-tracing = false
      pprof-enabled = true
      https-enabled = false
      https-certificate = "/etc/ssl/influxdb.pem"
      https-private-key = ""
      max-row-limit = 10000
      max-connection-limit = 0
      shared-secret = "beetlejuicebeetlejuicebeetlejuice"
      realm = "InfluxDB"
      unix-socket-enabled = false
      bind-socket = "/var/run/influxdb.sock"

    [continuous_queries]
      log-enabled = true
      enabled = true
      run-interval = "1s"
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitor
  labels:
    app: influxdb
    stack: tig
spec:
  type: ClusterIP
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    app: influxdb
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: influxdb
#  namespace: monitor
#  labels:
#    app: influxdb
#spec:
#  storageClassName: rook-ceph-block
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 3Gi
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: monitor
  labels:
    app: influxdb
    stack: tig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
      stack: tig
  template:
    metadata:
      labels:
        app: influxdb
        stack: tig
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.7-alpine
        env:
        - name: INFLUXDB_ADMIN_USER
          value: admin
        - name: INFLUXDB_ADMIN_PASSWORD
          value: admin
        resources:
          limits:
            cpu: 0.5
            memory: 1Gi
          requests:
            cpu: 0.1
            memory: 256Mi
        ports:
        - name: api
          containerPort: 8086
        livenessProbe:
          httpGet:
            path: /ping
            port: api
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: api
          initialDelaySeconds: 5
          timeoutSeconds: 1
        lifecycle:
          postStart:
            exec:
              command: 
              - /bin/bash 
              - -c
              - sleep 5;
              - /usr/bin/influx
                -precision rfc3339
                -username admin
                -password admin
                -execute 'ALTER RETENTION POLICY autogen ON telegraf DURATION 3d SHARD DURATION 1d'
        volumeMounts:
        - name: data
          mountPath: /var/lib/influxdb
        - name: config
          mountPath: /etc/influxdb
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/stack-tig
                operator: Exists
      volumes:
      - name: data
        hostPath:
          path: /var/lib/influxdb
          type: DirectoryOrCreate
      - name: config
        configMap:
          name: influxdb
