apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-monitor-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: redis-monitor
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: redis-monitor-sa
  namespace: default
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-monitor-script
  namespace: default
data:
  run.sh: |-
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-monitor
  namespace: default
  labels:
    app: redis-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-monitor
  template:
    metadata:
      labels:
        app: redis-monitor
    spec:
      containers:
      - name: alpine
        image: alpine:3.10
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "/tmp/run.sh"]
        volumeMounts:
        - name: runsh
          mountPath: /tmp
      serviceAccountName: redis-monitor-sa
      volumes:
      - name: runsh
        configMap:
          name: runsh
          defaultMode: 0755
