apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-conf
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;
      proxy_http_version 1.1;
      location / {
        root /usr/share/nginx/html;
      }
      location /v1/ {
        proxy_pass http://nginx-v1/;
      }
      location /v2/ {
        proxy_pass http://nginx-v2/;
      }
      location /v3/ {
        proxy_pass http://nginx-v3/;
      }
    }
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  selector:
    app: frontend
    version: v1
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: frontend-conf
        configMap:
          name: frontend-conf
