# Line 27-31
# limits: Maximim memory usage
# request: Minimum guaranteed memory usage

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trapacapp
  labels:
    component: trapac
    app: trapacapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: trapac
        app: trapacapp
    spec:
      containers:
      - image: 127.0.0.1:30001/trapacapp:Release-XXXXXX
        imagePullPolicy: IfNotPresent
        name: trapacapp
        envFrom:
        - configMapRef:
            name: trapacapp-config
        resources:
          limits:
            memory: "2Gi"
          requests:
            memory: "600Mi"
