{
 "title": "Kubernetes / Nodes - Alerts Template",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max (sum by (cpu) (irate(node_cpu_seconds_total{ job=\"node-exporter\", mode!=\"idle\", instance=\"10.140.0.33:9100\"}[2m])) ) * 100\n",
     "legendFormat": "10.140.0.33"
    },
    {
     "expr": "max (sum by (cpu) (irate(node_cpu_seconds_total{ job=\"node-exporter\", mode!=\"idle\", instance=\"10.140.0.34:9100\"}[2m])) ) * 100\n",
     "legendFormat": "10.140.0.34"
    },
    {
     "expr": "max (sum by (cpu) (irate(node_cpu_seconds_total{ job=\"node-exporter\", mode!=\"idle\", instance=\"10.140.0.35:9100\"}[2m])) ) * 100\n",
     "legendFormat": "10.140.0.35"
    },
    {
     "expr": "max (sum by (cpu) (irate(node_cpu_seconds_total{ job=\"node-exporter\", mode!=\"idle\", instance=\"10.140.0.36:9100\"}[2m])) ) * 100\n",
     "legendFormat": "10.140.0.36"
    },
    {
     "expr": "max (sum by (cpu) (irate(node_cpu_seconds_total{ job=\"node-exporter\", mode!=\"idle\", instance=\"10.140.0.37:9100\"}[2m])) ) * 100\n",
     "legendFormat": "10.140.0.37"
    },
    {
     "expr": "max (sum by (cpu) (irate(node_cpu_seconds_total{ job=\"node-exporter\", mode!=\"idle\", instance=\"10.140.0.38:9100\"}[2m])) ) * 100\n",
     "legendFormat": "10.140.0.38"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.140.0.33:9100\"}\n  - node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"10.140.0.33:9100\"}\n  - node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"10.140.0.33:9100\"}\n  - node_memory_Cached_bytes{job=\"node-exporter\", instance=\"10.140.0.33:9100\"}\n) / max(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.140.0.33:9100\"}) * 100",
     "legendFormat": "10.140.0.33"
    },
    {
     "expr": "max(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.140.0.34:9100\"}\n  - node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"10.140.0.34:9100\"}\n  - node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"10.140.0.34:9100\"}\n  - node_memory_Cached_bytes{job=\"node-exporter\", instance=\"10.140.0.34:9100\"}\n) / max(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.140.0.34:9100\"}) * 100",
     "legendFormat": "10.140.0.34"
    },
    {
     "expr": "max(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.140.0.35:9100\"}\n  - node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"10.140.0.35:9100\"}\n  - node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"10.140.0.35:9100\"}\n  - node_memory_Cached_bytes{job=\"node-exporter\", instance=\"10.140.0.35:9100\"}\n) / max(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.140.0.35:9100\"}) * 100",
     "legendFormat": "10.140.0.35"
    },
    {
     "expr": "max(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.140.0.36:9100\"}\n  - node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"10.140.0.36:9100\"}\n  - node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"10.140.0.36:9100\"}\n  - node_memory_Cached_bytes{job=\"node-exporter\", instance=\"10.140.0.36:9100\"}\n) / max(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.140.0.36:9100\"}) * 100",
     "legendFormat": "10.140.0.36"
    },
    {
     "expr": "max(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.140.0.37:9100\"}\n  - node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"10.140.0.37:9100\"}\n  - node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"10.140.0.37:9100\"}\n  - node_memory_Cached_bytes{job=\"node-exporter\", instance=\"10.140.0.37:9100\"}\n) / max(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.140.0.37:9100\"}) * 100",
     "legendFormat": "10.140.0.37"
    },
    {
     "expr": "max(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.140.0.38:9100\"}\n  - node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"10.140.0.38:9100\"}\n  - node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"10.140.0.38:9100\"}\n  - node_memory_Cached_bytes{job=\"node-exporter\", instance=\"10.140.0.38:9100\"}\n) / max(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.140.0.38:9100\"}) * 100",
     "legendFormat": "10.140.0.38"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max by (namespace, pod, device) (\n  (\n    node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.33:9100\", job=\"node-exporter\"} -\n    node_filesystem_avail_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.33:9100\", job=\"node-exporter\"}\n  ) / node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.33:9100\", job=\"node-exporter\"}\n) * 100",
     "legendFormat": "10.140.0.33"
    },
    {
     "expr": "max by (namespace, pod, device) (\n  (\n    node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.34:9100\", job=\"node-exporter\"} -\n    node_filesystem_avail_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.34:9100\", job=\"node-exporter\"}\n  ) / node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.34:9100\", job=\"node-exporter\"}\n) * 100",
     "legendFormat": "10.140.0.34"
    },
    {
     "expr": "max by (namespace, pod, device) (\n  (\n    node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.35:9100\", job=\"node-exporter\"} -\n    node_filesystem_avail_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.35:9100\", job=\"node-exporter\"}\n  ) / node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.35:9100\", job=\"node-exporter\"}\n) * 100",
     "legendFormat": "10.140.0.35"
    },
    {
     "expr": "max by (namespace, pod, device) (\n  (\n    node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.36:9100\", job=\"node-exporter\"} -\n    node_filesystem_avail_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.36:9100\", job=\"node-exporter\"}\n  ) / node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.36:9100\", job=\"node-exporter\"}\n) * 100",
     "legendFormat": "10.140.0.36"
    },
    {
     "expr": "max by (namespace, pod, device) (\n  (\n    node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.37:9100\", job=\"node-exporter\"} -\n    node_filesystem_avail_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.37:9100\", job=\"node-exporter\"}\n  ) / node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.37:9100\", job=\"node-exporter\"}\n) * 100",
     "legendFormat": "10.140.0.37"
    },
    {
     "expr": "max by (namespace, pod, device) (\n  (\n    node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.38:9100\", job=\"node-exporter\"} -\n    node_filesystem_avail_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.38:9100\", job=\"node-exporter\"}\n  ) / node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint=\"/\", instance=\"10.140.0.38:9100\", job=\"node-exporter\"}\n) * 100",
     "legendFormat": "10.140.0.38"
    }
   ]
  }
 ]
}